import Link from "next/link";
import { Notice } from "@/components/Notice";
import { JourneyRuleForm } from "@/components/JourneyRuleForm";
import { requireWorkspace } from "@/lib/auth";
import { setJourneyEnabledAction, saveJourneyStageAction, saveJourneyRuleAction } from "@/lib/journey-actions";
import { journeyRuleRevision, journeyRuleWhen } from "@/lib/journey-types";
import { prisma } from "@/lib/prisma";
export const metadata = { title: "Customer journey settings" };
export default async function JourneySettings({ searchParams }: { searchParams: Promise<{ saved?: string; error?: string; stage?: string }> }) {
  const [{ workspace }, query] = await Promise.all([requireWorkspace(), searchParams]);
  const [preference, stages, plans] = await Promise.all([
    prisma.journeyPreference.findUnique({ where: { workspaceId: workspace.id } }),
    prisma.journeyStage.findMany({ where: { workspaceId: workspace.id }, include: { outgoingRules: { include: { toStage: true } }, plan: true, _count: { select: { contacts: true } } }, orderBy: [{ position: "asc" }, { id: "asc" }] }),
    prisma.mix.findMany({ where: { workspaceId: workspace.id, status: "ACTIVE", triggerMode: "MANUAL_START", source: { not: "ONE_TIME" } }, select: { id: true, name: true }, orderBy: { name: "asc" } })
  ]);
  const activeStages = stages.filter(stage => stage.isActive);
  const ruleStages = activeStages.map(stage => ({ id: stage.id, name: stage.name, planName: stage.plan?.status === "ACTIVE" ? stage.plan.name : null }));
  return <div className="page"><header className="page-header"><div><h1>Make the journey yours</h1><p>Choose the stages, triggers, and follow-ups that fit your business.</p></div><Link className="button" href="/journey">View journey</Link></header>
    {query.error && <Notice type="error">{query.error}</Notice>}{query.saved && <Notice type="success">Journey settings saved.</Notice>}
    <section className="card"><h2>{preference ? preference.enabled ? "Automatic transitions are on" : "Automatic transitions are paused" : "Start with a simple journey"}</h2>{preference ? <><p className="journey-saved-stages">{activeStages.map(stage => stage.name).join(" → ")}</p><p>Your rules decide how people move. They can skip stages or return to an earlier one; the order above organizes your view.</p></> : <p>Start with Lead → Prospect → Client → Retention, then rename stages and choose the events that matter to your business.</p>}
      <p className="muted-copy">Existing contacts keep their history and stay unassigned until you choose a stage or record a milestone. {preference ? <>New contacts use the rules for <strong>{activeStages[0]?.name}</strong>, your first stage.</> : "New contacts use the rules for the first stage."} Changing a stage’s mix applies when someone next enters it; people already there keep their current mix.</p><form action={setJourneyEnabledAction}><input type="hidden" name="enabled" value={String(!preference?.enabled)} /><button className={`button ${preference?.enabled ? "" : "primary"}`}>{preference ? preference.enabled ? "Pause automatic transitions" : "Resume automatic transitions" : "Use this starting journey"}</button></form></section>
    {stages.map(stage => <details className="card journey-stage-settings" key={stage.id} id={`stage-${stage.id}`} open={query.stage === stage.id || undefined}><summary><strong>{stage.name}</strong><span>{stage.isActive ? `${stage._count.contacts} ${stage._count.contacts === 1 ? "person" : "people"} · ${stage.plan?.name ?? "No mix assigned"}` : "Retired"}</span></summary>
      <form action={saveJourneyStageAction} className="form-grid"><input type="hidden" name="stageId" value={stage.id} /><label className="field"><span>Stage name</span><input name="name" defaultValue={stage.name} maxLength={60} required /></label><label className="field"><span>Follow-up mix on entry</span><select name="planId" defaultValue={stage.planId ?? ""}><option value="">No automatic mix</option>{stage.plan && !plans.some(plan => plan.id === stage.planId) && <option value={stage.planId!}>{stage.plan.name} (not active)</option>}{plans.map(plan => <option value={plan.id} key={plan.id}>{plan.name}</option>)}</select></label><div className="form-actions field full"><button className="button primary" name="intent" value="save">{stage.isActive ? "Save stage" : "Restore stage"}</button>{stage.isActive && <><button className="button" name="intent" value="earlier" formNoValidate disabled={stages.find(item => item.isActive)?.id === stage.id}>Move earlier</button><button className="button" name="intent" value="later" formNoValidate disabled={stages.filter(item => item.isActive).at(-1)?.id === stage.id}>Move later</button><button className="button danger" name="intent" value="archive" formNoValidate>Retire empty stage</button></>}</div></form>
      <h3>Automatic transition rules</h3>{!stage.outgoingRules.some(rule => rule.enabled) && <p className="muted-copy">No automatic moves from this stage. People stay here until you move them or add a rule.</p>}{stage.outgoingRules.filter(rule => rule.enabled).map(rule => <div className="journey-rule-row" key={rule.id}><div><p>{journeyRuleWhen(rule.eventType, rule.afterDays)} → <strong>{rule.toStage.name}</strong></p>{stage.isActive && <details><summary aria-label={`Edit rule: ${journeyRuleWhen(rule.eventType, rule.afterDays)} to ${rule.toStage.name}`}>Edit rule</summary><JourneyRuleForm key={stage.outgoingRules.map(journeyRuleRevision).join(":")} fromStageId={stage.id} stages={ruleStages} rules={stage.outgoingRules} initialEventType={rule.eventType} automatic={Boolean(preference?.enabled)} /></details>}</div><form action={saveJourneyRuleAction}><input type="hidden" name="fromStageId" value={stage.id} /><input type="hidden" name="eventType" value={rule.eventType} /><input type="hidden" name="expectedRule" value={journeyRuleRevision(rule)} /><button className="button small" name="intent" value="remove" aria-label={`Remove rule: ${journeyRuleWhen(rule.eventType, rule.afterDays)} to ${rule.toStage.name}`}>Remove rule</button></form></div>)}
      {stage.isActive && <details><summary>Add or change a rule</summary><JourneyRuleForm key={stage.outgoingRules.map(journeyRuleRevision).join(":")} fromStageId={stage.id} stages={ruleStages} rules={stage.outgoingRules} automatic={Boolean(preference?.enabled)} /></details>}
    </details>)}
    {!!stages.length && <details className="card"><summary>Add another stage</summary><form action={saveJourneyStageAction} className="form-stack"><label className="field"><span>Stage name</span><input name="name" maxLength={60} placeholder="For example, Proposal or Past customer" required /></label><button className="button primary">Add stage</button></form></details>}
    <p className="muted-copy">Only the previous stage’s managed mix is stopped when someone moves on. Other mixes, manual stops, and Do not contact preferences are respected. Pausing transitions does not pause mixes that are already running.</p>
  </div>;
}
