/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=infra/cloudflare-scheduler/wrangler.jsonc --include-runtime=false --strict-vars=false --env-interface=JitmSchedulerEnv infra/cloudflare-scheduler/worker-configuration.d.ts` (hash: cbe5e581b7ebca57ae218d2d2f48a72e)
interface __BaseEnv_JitmSchedulerEnv {
	APP_URL: string;
	NETLIFY_WORKER_SECRET: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./index");
	}
	interface Env extends __BaseEnv_JitmSchedulerEnv {}
}
interface JitmSchedulerEnv extends __BaseEnv_JitmSchedulerEnv {}
