import Link from "next/link";
import { randomUUID } from "node:crypto";
import { requireWorkspace } from "@/lib/auth";
import { prisma } from "@/lib/prisma";
import { env } from "@/lib/env";
import { localCalendarTime } from "@/lib/calendar-time";
import { zonedDateTimeToUtc } from "@/lib/jump-schedule";
import { decryptIntegrationCredentials, integrationEncryptionConfigured } from "@/lib/integration-crypto";
import { calendarConnectionAction, cancelCalendarAction } from "@/lib/calendar-actions";
import { CalendarEntryForm } from "@/components/CalendarEntryForm";
import { CopyField } from "@/components/CopyField";
import { Notice } from "@/components/Notice";
import { ConfirmDialog } from "@/components/ConfirmDialog";
export const metadata = { title: "Calendar" };

export default async function CalendarPage({ searchParams }: { searchParams: Promise<{ date?: string; contact?: string; edit?: string; q?: string; saved?: string; error?: string }> }) {
  const [{ workspace, user, impersonation }, query] = await Promise.all([requireWorkspace(), searchParams]);
  const preference = await prisma.userPreference.findUnique({ where: { userId: user.id } });
  const timezone = preference?.timezone || "UTC";
  const requestedDate = /^\d{4}-\d{2}-\d{2}$/.test(query.date ?? "") ? new Date(`${query.date}T12:00:00Z`) : null;
  const date = requestedDate && requestedDate.getUTCFullYear() >= 2000 && requestedDate.getUTCFullYear() <= 2100 && Number.isFinite(requestedDate.getTime()) && requestedDate.toISOString().slice(0,10) === query.date ? query.date! : localCalendarTime(new Date(), timezone).slice(0,10);
  const dayDate = (offset: number) => new Date(new Date(`${date}T12:00:00Z`).getTime() + offset * 86_400_000);
  const midnight = (offset: number) => { const d = dayDate(offset); return zonedDateTimeToUtc({ year: d.getUTCFullYear(), month: d.getUTCMonth()+1, day: d.getUTCDate() }, 0, timezone); };
  const [entries, connections, share, editing, contacts, chosen] = await Promise.all([
    prisma.calendarEntry.findMany({ where: { workspaceId: workspace.id, canceledAt: null, startsAt: { lt: midnight(7) }, endsAt: { gt: midnight(0) } }, include: { contact: { select: { displayName: true } }, connection: { select: { name: true } } }, orderBy: [{ startsAt: "asc" }, { id: "asc" }], take: 500 }),
    prisma.calendarConnection.findMany({ where: { workspaceId: workspace.id }, orderBy: { createdAt: "desc" } }),
    prisma.calendarPreference.findUnique({ where: { workspaceId: workspace.id } }),
    query.edit ? prisma.calendarEntry.findFirst({ where: { id: query.edit, workspaceId: workspace.id, canceledAt: null, connectionId: null } }) : null,
    prisma.contact.findMany({ where: { workspaceId: workspace.id, archivedAt: null, ...(query.q?.trim() ? { displayName: { contains: query.q.trim().slice(0,160), mode: "insensitive" } } : {}) }, select: { id: true, displayName: true }, orderBy: [{ displayName: "asc" }, { id: "asc" }], take: 200 }),
    query.contact ? prisma.contact.findFirst({ where: { id: query.contact, workspaceId: workspace.id, archivedAt: null }, select: { id: true, displayName: true } }) : null
  ]);
  if (chosen && !contacts.some(contact => contact.id === chosen.id)) contacts.unshift(chosen);
  if (editing?.contactId && !contacts.some(contact => contact.id === editing.contactId)) {
    const contact = await prisma.contact.findFirst({ where: { id: editing.contactId, workspaceId: workspace.id }, select: { id: true, displayName: true } });
    if (contact) contacts.unshift(contact);
  }
  let subscriptionUrl = "";
  if (share && !impersonation) { try { subscriptionUrl = `${env.appUrl}/api/calendar/feed/${decryptIntegrationCredentials<string>(share.tokenEncrypted)}`; } catch { /* Rotation restores unreadable keys. */ } }
  const format = (value: Date) => new Intl.DateTimeFormat("en", { timeZone: timezone, month: "short", day: "numeric", hour: "numeric", minute: "2-digit" }).format(value);
  return <div className="page calendar-page"><header className="page-header"><div><h1>Calendar</h1><p>Make space for conversations and the work between them.</p></div><div className="page-actions"><Link className="button primary" href="#schedule-event">Schedule an event</Link><a className="button" href="/api/calendar/export">Download calendar</a></div></header>
    {query.saved && <Notice>Calendar updated.</Notice>}{query.error && <Notice type="error">{query.error}</Notice>}
    {connections.some(connection => connection.lastError || !connection.lastSyncedAt || Date.now()-connection.lastSyncedAt.getTime() > 24*3_600_000) && <Notice type="info">Some connected availability may be out of date. Review <a href="#calendar-connections" className="inline-action">calendar connections</a> before booking.</Notice>}
    <section className="card"><div className="section-label"><h2>Your next seven days</h2><span>{timezone}</span></div><form className="filter-bar" action="/calendar"><label className="field"><span>Starting date</span><input type="date" name="date" defaultValue={date} required /></label><button className="button">Show dates</button></form><nav className="calendar-week-nav" aria-label="Calendar weeks"><Link className="button" href={`/calendar?date=${dayDate(-7).toISOString().slice(0,10)}`}>Previous week</Link><Link className="button" href="/calendar">Today</Link><Link className="button" href={`/calendar?date=${dayDate(7).toISOString().slice(0,10)}`}>Next week</Link></nav>
      <div className="calendar-agenda">{Array.from({ length: 7 }, (_, index) => {
        const start = midnight(index), end = midnight(index+1); const dayEntries = entries.filter(entry => entry.startsAt < end && entry.endsAt > start);
        return <section className="calendar-day" key={index}><h3>{new Intl.DateTimeFormat("en", { timeZone: "UTC", weekday: "short", month: "short", day: "numeric" }).format(dayDate(index))}</h3>{dayEntries.length ? dayEntries.map(entry => <article className={`calendar-event ${entry.kind.toLowerCase()}`} key={entry.id}><div><span className="eyebrow">{entry.kind === "MEETING" ? "Meeting" : entry.kind === "BLOCK" ? "Time block" : "Connected calendar"}</span><h4>{entry.title}</h4>{entries.some(other => other.id !== entry.id && other.startsAt < entry.endsAt && other.endsAt > entry.startsAt) && <span className="status-pill">Overlaps another event</span>}<p><time dateTime={entry.startsAt.toISOString()}>{format(entry.startsAt)}</time> – <time dateTime={entry.endsAt.toISOString()}>{format(entry.endsAt)}</time></p>{entry.contact && <Link className="inline-action" href={`/contacts/${entry.contactId}`}>{entry.contact.displayName}</Link>}{entry.connection && <small>{entry.connection.name}</small>}</div>{!entry.connectionId && <div className="form-actions"><Link className="button small" href={`/calendar?edit=${entry.id}&date=${date}#schedule-event`}>Edit</Link><a className="button small" href={`/api/calendar/export?id=${entry.id}`}>Download</a><ConfirmDialog trigger="Cancel event…" title={`Cancel ${entry.title}?`} description="This removes its reserved time. The contact’s current journey stage stays in place."><form action={cancelCalendarAction}><input type="hidden" name="id" value={entry.id} /><input type="hidden" name="version" value={entry.version} /><button className="button danger">Cancel event</button></form></ConfirmDialog></div>}</article>) : <p className="muted-copy">No time reserved.</p>}</section>;
      })}</div>{entries.length === 500 && <Notice type="info">Showing the first 500 events for these dates. Disconnect unused calendars to reduce the list.</Notice>}
    </section>
    <section className="card" id="schedule-event"><h2>{editing ? "Edit event" : chosen ? `Make time for ${chosen.displayName}` : "Schedule a meeting or time block"}</h2>
      <details><summary>Find a contact for this event</summary><form className="filter-bar" action="/calendar#schedule-event"><input type="hidden" name="date" value={date} />{editing && <input type="hidden" name="edit" value={editing.id} />}<input name="q" type="search" aria-label="Find a calendar contact" placeholder="Search contact names" defaultValue={query.q} /><button className="button">Find contacts</button></form><p className="muted-copy">The contact menu shows up to 200 matches. You can also schedule directly from any contact’s page.</p></details>
      <CalendarEntryForm key={randomUUID()} contacts={contacts} contactId={chosen?.id} timezone={editing?.timezone ?? timezone} locale={preference?.locale || undefined} date={date} entry={editing ? { id: editing.id, version: editing.version, title: editing.title, kind: editing.kind, contactId: editing.contactId, startsAt: localCalendarTime(editing.startsAt, editing.timezone), endsAt: localCalendarTime(editing.endsAt, editing.timezone) } : undefined} />
    </section>
    <section className="card" id="calendar-connections"><h2>Bring your calendars together</h2><p>Google Calendar, Outlook, Apple Calendar, and other iCalendar providers can share availability here. Add a subscription URL for automatic refreshes, or import an .ics file for a snapshot.</p><p className="muted-copy">Incoming calendars show busy time from the past month through the next year. Subscriptions are checked about every 15 minutes while the worker runs. Imported files stay as they were when uploaded. Edit external events in their original calendar.</p>
      {connections.map(connection => <div className="connection-row" key={connection.id}><div><h3>{connection.name}</h3><p>{connection.urlEncrypted ? "Subscription" : "Imported file"} · {connection.lastSyncedAt ? `Last updated ${format(connection.lastSyncedAt)}` : "Not refreshed yet"}</p>{connection.lastError && <Notice type="error">{connection.lastError}</Notice>}</div><div className="form-actions">{connection.urlEncrypted && <form action={calendarConnectionAction}><input type="hidden" name="id" value={connection.id} /><button className="button small" name="intent" value="sync">Refresh now</button></form>}<ConfirmDialog trigger="Disconnect…" title={`Disconnect ${connection.name}?`} description="Its imported availability will be removed from this calendar."><form action={calendarConnectionAction}><input type="hidden" name="id" value={connection.id} /><button className="button danger" name="intent" value="disconnect">Disconnect calendar</button></form></ConfirmDialog></div></div>)}
      <details><summary>Connect a calendar subscription</summary>{integrationEncryptionConfigured() ? <form action={calendarConnectionAction} className="form-stack"><label className="field"><span>Calendar name</span><input name="name" maxLength={100} placeholder="For example, Work calendar" required /></label><label className="field"><span>iCalendar subscription URL</span><input name="url" type="text" placeholder="https://…/calendar.ics" maxLength={4096} required /></label><label className="field"><span>Calendar timezone</span><input name="timezone" defaultValue={timezone} required /></label><p className="muted-copy">In Google, copy the secret iCal address from calendar settings. In Outlook, use Publish a calendar → ICS. In Apple, use the shared calendar’s link. Provider sharing settings determine who can access that link; keep it private.</p><button className="button primary" name="intent" value="connect">Connect calendar</button></form> : <p>Calendar subscriptions are unavailable until this installation enables encrypted connections. File import is available below.</p>}</details>
      <details><summary>Import a calendar file</summary><form action={calendarConnectionAction} className="form-stack"><label className="field"><span>Imported calendar name</span><input name="name" maxLength={100} required /></label><label className="field"><span>iCalendar file</span><input name="file" type="file" accept=".ics,text/calendar" required /></label><label className="field"><span>File timezone</span><input name="timezone" defaultValue={timezone} required /></label><button className="button" name="intent" value="import">Import availability</button></form></details>
      <details><summary>Show Jump in the Mix in another calendar</summary><p>Subscribe using “Add calendar from URL” in your provider. It will show meetings and time blocks created here. Refresh timing is controlled by your provider; edits travel from Jump in the Mix to that calendar.</p>{env.privateTestMode && <Notice type="info">This private test site also requires its access credentials. Providers that cannot supply them can use the calendar download instead.</Notice>}{subscriptionUrl ? <><p>Anyone with this private link can read event titles and times. Share it only with your calendar provider.</p><CopyField label="Subscription URL" value={subscriptionUrl} /><div className="form-actions"><ConfirmDialog trigger="Replace private link…" title="Replace this calendar link?" description="Existing calendar subscriptions will need the new link."><form action={calendarConnectionAction}><button className="button" name="intent" value="rotate">Replace link</button></form></ConfirmDialog><form action={calendarConnectionAction}><button className="button" name="intent" value="revoke">Disable subscription</button></form></div></> : <form action={calendarConnectionAction}><button className="button" name="intent" value="subscribe" disabled={!integrationEncryptionConfigured() || Boolean(impersonation)}>Create private subscription link</button></form>}<p><a className="inline-action" href="/api/calendar/export">Download an .ics file</a> for a one-time copy instead.</p></details>
    </section>
  </div>;
}
