import Link from "next/link";
import { Logo } from "@/components/Logo";

export default function HomePage() {
  return <main className="public-page">
    <header className="public-header"><Logo/><nav aria-label="Public navigation"><a href="#how-it-works">How it works</a><a href="#features">Features</a><Link className="button" href="/login">Sign in</Link><Link className="button primary" href="/register">Create account</Link></nav></header>
    <section className="hero"><div className="hero-copy"><span className="eyebrow">The follow-up CRM for busy local businesses</span><h1>Turn today’s customers into tomorrow’s repeat jobs and referrals.</h1><p>Jump in the Mix prepares the texts, calls, and emails that keep estimates moving, customers cared for, and your business top of mind.</p><div className="hero-actions"><Link className="button primary" href="/register">Start free</Link><Link className="button" href="/login">Sign in</Link></div><small>Built for home services, real estate, insurance, and other owner-operated businesses.</small></div></section>
    <section className="section" id="how-it-works"><div className="section-heading"><span className="eyebrow">Ready in minutes</span><h2>Open Today and know who to contact next.</h2></div><div className="step-grid"><article className="step-card"><div className="number-badge">1</div><h3>Choose your business</h3><p>Start with practical plans for finished jobs, estimates, new leads, renewals, and past customers.</p></article><article className="step-card"><div className="number-badge">2</div><h3>Add a customer</h3><p>Save a name and phone number, then choose when you want to follow up.</p></article><article className="step-card"><div className="number-badge">3</div><h3>Work from Today</h3><p>Review the prepared message, open text or email, and record what happened in a few taps.</p></article></div></section>
    <section className="section" id="features"><div className="section-heading"><span className="eyebrow">Less admin, better follow-through</span><h2>A lightweight CRM that fits in your pocket.</h2></div><div className="trust-grid"><article><h3>Never lose an estimate</h3><p>Gentle reminders show up when they matter, with a useful message ready to go.</p></article><article><h3>Earn more reviews and referrals</h3><p>Use proven post-job plans that feel warm, personal, and never pushy.</p></article><article><h3>Own your customer history</h3><p>Notes, completed follow-ups, exports, encrypted backups, and privacy controls stay under your control.</p></article></div></section>
    <section className="section"><div className="section-heading"><span className="eyebrow">You approve every message</span><h2>Helpful automation without losing your voice.</h2><p>Review or edit each message before it opens in your phone’s text or email app. You decide what gets sent.</p></div></section>
  </main>;
}
