import Link from "next/link";
import { Logo } from "@/components/Logo";

export default function HomePage() {
  return <main className="public-page">
    <header className="public-header"><Logo/><nav aria-label="Public navigation"><a href="#how-it-works">How it works</a><a href="#features">Features</a><Link className="button" href="/login">Sign in</Link><Link className="button primary" href="/register">Create account</Link></nav></header>
    <section className="hero"><div className="hero-copy"><span className="eyebrow">Personal relationship follow-up</span><h1>Remember the person, the moment, and the next action.</h1><p>Jump in the Mix gives one person a clear place for Contacts, Important Dates, follow-up plans, and the actions that matter today.</p><div className="hero-actions"><Link className="button primary" href="/register">Get started</Link><Link className="button" href="/login">Sign in</Link></div></div></section>
    <section className="section" id="how-it-works"><div className="section-heading"><span className="eyebrow">A simple rhythm</span><h2>Structure without CRM clutter.</h2></div><div className="step-grid"><article className="step-card"><div className="number-badge">1</div><h3>Add the people who matter</h3><p>Create a Contact or import a CSV or VCF file, then keep communication details and relationship notes together.</p></article><article className="step-card"><div className="number-badge">2</div><h3>Build a follow-up plan</h3><p>Create a Mix from scratch or start from a reusable template. Choose the audience, timing, and actions yourself.</p></article><article className="step-card"><div className="number-badge">3</div><h3>Work from Today</h3><p>Open prepared actions, record the outcome, schedule the next follow-up, and keep your relationship timeline current.</p></article></div></section>
    <section className="section" id="features"><div className="section-heading"><span className="eyebrow">Everything in its place</span><h2>Focused tools for personal and professional relationships.</h2></div><div className="trust-grid"><article><h3>Contacts</h3><p>Search names, companies, phones, emails, customer notes, and private relationship updates.</p></article><article><h3>Mixes and Templates</h3><p>Write action content directly, reuse templates when useful, and review workload before activation.</p></article><article><h3>Personal data controls</h3><p>Export your data, manage active sessions, or permanently delete your account from one clear settings area.</p></article></div></section>
    <section className="section"><div className="section-heading"><span className="eyebrow">You stay in control</span><h2>Prepared actions, reviewed by you.</h2><p>Jumps open the native communication channel with prepared content. You decide what to send and record what happened.</p></div></section>
  </main>;
}
