import Link from "next/link";
import { Logo } from "@/components/Logo";
import { ProductDemo } from "@/components/ProductDemo";

export default function HomePage() {
  return <main className="public-page">
    <header className="public-header"><Logo /><nav aria-label="Public navigation"><a href="#how-it-works">How it works</a><a href="#features">Features</a><Link className="button" href="/login">Sign in</Link><Link className="button primary" href="/register">Create account</Link></nav></header>
    <section className="hero"><div className="hero-copy"><span className="eyebrow">For the business you’re building</span><h1>Good work deserves a <em>follow-up.</em></h1><p>Keep estimates moving and customers coming back. Jump in the Mix brings your people, prepared messages, and next steps into one simple daily list.</p><div className="hero-actions"><Link className="button primary" href="/register">Start free</Link><a className="button" href="#how-it-works">See how it works</a></div><p className="hero-note">Made for owner-operated businesses. Ready on your phone.</p></div><ProductDemo /></section>
    <section className="section" id="how-it-works"><div className="section-heading"><span className="eyebrow">From busy to on top of it</span><h2>One place to pick up where you left off.</h2></div><div className="step-grid"><article className="step-card"><div className="number-badge">01</div><h3>Bring your people</h3><p>Add a customer in a few taps, or import the contacts you already have.</p></article><article className="step-card"><div className="number-badge">02</div><h3>Find your rhythm</h3><p>Choose a ready-made plan for estimates, finished jobs, renewals, or keeping in touch. Make every message your own.</p></article><article className="step-card"><div className="number-badge">03</div><h3>Make today count</h3><p>Open Today, see who needs a follow-up, and record what happened. Your next step is ready.</p></article></div></section>
    <section className="section" id="features"><div className="section-heading"><span className="eyebrow">Small touches. Stronger relationships.</span><h2>Be the business people remember.</h2></div><div className="trust-grid"><article><h3>Give estimates a next step</h3><p>Follow up with a useful question and keep the conversation moving.</p></article><article><h3>Stay close after the job</h3><p>Check that everything went well, ask for feedback, and be there when customers need you again.</p></article><article><h3>Keep the whole story</h3><p>Contact details, notes, and completed follow-ups stay together. Export your data whenever you need it.</p></article></div></section>
    <section className="section public-control"><div className="section-heading"><span className="eyebrow">Your voice. Your choice.</span><h2>A personal touch, with a little help.</h2><p>Review and send messages yourself by default. When available, optional automatic sending follows the plans and review window you choose. Calls always stay in your hands.</p></div><Link className="button primary" href="/register">Build your first plan</Link></section>
    <footer className="public-footer"><Logo /><p>A little follow-through goes a long way.</p><nav aria-label="Footer navigation"><Link href="/login">Sign in</Link><Link href="/register">Create account</Link></nav></footer>
  </main>;
}
