import Link from "next/link";
import { requireWorkspace } from "@/lib/auth";
import { journeyEventLabel } from "@/lib/journey-types";
import { env } from "@/lib/env";
import { prisma } from "@/lib/prisma";
import { INTAKE_KINDS, intakeKindLabel } from "@/lib/intake-types";
import { intakeConnectionAction, reviewIntakeAction } from "@/lib/intake-actions";
import { intakeMatches, parseIntakePayload } from "@/lib/intake";
import { decryptIntegrationCredentials, integrationEncryptionConfigured } from "@/lib/integration-crypto";
import { CopyField } from "@/components/CopyField";
import { Notice } from "@/components/Notice";
import { ConfirmDialog } from "@/components/ConfirmDialog";
export const metadata = { title: "Lead connections" };
export default async function LeadConnectionsPage({ searchParams }: { searchParams: Promise<{ selected?: string; saved?: string; error?: string; page?: string }> }) {
  const [{ workspace, impersonation }, query] = await Promise.all([requireWorkspace(), searchParams]);
  const page = Math.max(1, Math.min(10000, Number.parseInt(query.page ?? "1", 10) || 1));
  const [connections, reviews, reviewCount, recent, recentCount] = await Promise.all([
    prisma.intakeConnection.findMany({ where: { workspaceId: workspace.id }, include: { _count: { select: { receipts: true } } }, orderBy: [{ createdAt: "desc" }, { id: "asc" }] }),
    prisma.intakeReceipt.findMany({ where: { connection: { workspaceId: workspace.id }, status: "REVIEW" }, include: { connection: true }, orderBy: [{ createdAt: "asc" }, { id: "asc" }], take: 10 }),
    prisma.intakeReceipt.count({ where: { connection: { workspaceId: workspace.id }, status: "REVIEW" } }),
    prisma.intakeReceipt.findMany({ where: { connection: { workspaceId: workspace.id } }, include: { connection: { select: { name: true } }, contact: { select: { displayName: true } } }, orderBy: [{ createdAt: "desc" }, { id: "asc" }], skip: (page-1)*20, take: 20 }),
    prisma.intakeReceipt.count({ where: { connection: { workspaceId: workspace.id } } })
  ]);
  const reviewData = await Promise.all(reviews.map(async receipt => { const payload = parseIntakePayload(receipt.payload); return { receipt, payload, matches: await intakeMatches(prisma, workspace.id, receipt.connectionId, payload) }; }));
  return <div className="page connections-page"><header className="page-header"><div><h1>Every inquiry, one place</h1><p>Connect the channels your business already uses.</p></div><Link className="button" href="/contacts/import">Import CSV or vCard</Link></header>
    {query.saved && <Notice>Connection settings saved.</Notice>}{query.error && <Notice type="error">{query.error}</Notice>}
    <div className="connection-paths"><section className="card"><span className="eyebrow">Ready to share</span><h2>A simple lead form</h2><p>Share a link from your website, social bio, email, or QR code. New inquiries arrive here automatically.</p><a className="button" href="#add-connection">Create a form</a></section><section className="card"><span className="eyebrow">Fits your tools</span><h2>Connect an existing source</h2><p>Use your provider’s automation, Zapier, Make, n8n, or a small integration to send inquiries and milestones here.</p><a className="button" href="#source-guide">Find your source</a></section></div>
    <section className="card" id="add-connection"><h2>Add a lead connection</h2>{integrationEncryptionConfigured() ? <form action={intakeConnectionAction} className="form-grid"><label className="field"><span>Connection name</span><input name="name" placeholder="For example, Website inquiries" maxLength={100} required /></label><label className="field"><span>Source</span><select name="kind" defaultValue="HOSTED_FORM">{INTAKE_KINDS.map(kind => <option key={kind.value} value={kind.value}>{kind.label}</option>)}</select></label><div className="form-actions field full"><button className="button primary" name="intent" value="create">Create connection</button></div></form> : <Notice type="info">Lead connections are unavailable until this installation enables encrypted connections. You can still import CSV and vCard files.</Notice>}</section>
    <section aria-label="Your lead connections">{connections.map(connection => {
      const endpoint = `${env.appUrl}/api/webhooks/intake/${connection.id}`; const formUrl = `${env.appUrl}/lead/${connection.id}`;
      let token = ""; if (!impersonation) { try { token = decryptIntegrationCredentials<string>(connection.tokenEncrypted); } catch { /* Replace key through the action below. */ } }
      return <details className="card connection-setup" key={connection.id} open={query.selected === connection.id}><summary><strong>{connection.name}</strong><span>{connection.enabled ? "Enabled" : "Paused"} · {intakeKindLabel(connection.kind)} · {connection._count.receipts} inquiries</span></summary>
        {connection.kind === "HOSTED_FORM" ? <><CopyField label="Form link" value={formUrl} /><p><a className="inline-action" href={formUrl}>Open your form</a>. Paste this link into your website’s contact button, social bio, or QR code tool.</p></> : <><ol className="connection-steps"><li>Choose the event in your source tool, such as a new form submission or incoming message.</li><li>Add an HTTP POST step using the endpoint below. Set Content-Type to application/json and X-JITM-Key to this connection’s private key.</li><li>Map the contact fields using the example. Use your source event’s unique ID as eventId and its person ID as externalId. Keep eventId unchanged when retrying.</li><li>Test with a sample contact, then enable the automation in your source tool. Check Recent inquiries below for its receipt.</li></ol><CopyField label="Endpoint" value={endpoint} />{token && <CopyField label="Private key" value={token} secret />}<CopyField label="Example JSON" multiline value={JSON.stringify({ eventId: "replace-with-source-event-id", externalId: "replace-with-source-person-id", displayName: "Sample person", email: "sample@example.com", phone: "+14155550123", company: "Sample business", message: "Interested in learning more", eventType: "CONTACT_RECEIVED" }, null, 2)} />
          <details><summary>Fields, business milestones, and responses</summary><p>eventId is required, along with email, phone, or externalId. Names, company, and message are optional. Phone numbers should include a country code. Omit fields your source does not provide.</p><p>Use CONTACT_RECEIVED for inquiries. Trusted sources can also record CONVERSATION_STARTED, MEETING_SCHEDULED, SALE_CONFIRMED, or WORK_COMPLETED to run your journey rules. Sending a message alone does not confirm a sale.</p><p>201 means accepted; 200 means the same event was already received; 202 means a person needs review. 409 means an eventId was reused with changed details. For 429, wait for Retry-After; for 503, retry the same event. Limit: 60 requests per minute per connection.</p><p>Keep this key in your backend or automation tool. A browser form should use your backend or the hosted form; never publish the key in website code.</p></details>
          <ConfirmDialog trigger="Replace private key…" title="Replace this connection’s key?" description="Your source tool must be updated with the new key before it can send more inquiries."><form action={intakeConnectionAction}><input type="hidden" name="id" value={connection.id} /><button className="button" name="intent" value="rotate">Replace key</button></form></ConfirmDialog></>}
        {env.privateTestMode && <Notice type="info">This private test site also requires its access credentials. External tools must supply Basic authentication as well as X-JITM-Key; shareable forms require the site’s private access.</Notice>}
        <form action={intakeConnectionAction}><input type="hidden" name="id" value={connection.id} /><input type="hidden" name="enabled" value={String(!connection.enabled)} /><button className="button" name="intent" value="toggle">{connection.enabled ? "Pause this connection" : "Resume this connection"}</button></form>
      </details>;
    })}</section>
    <section className="card" id="needs-review"><h2>Needs a person’s eye{reviewCount ? ` · ${reviewCount}` : ""}</h2><p>Exact email, phone, and source IDs prevent duplicate contacts. When details point to different people or an archived contact, we hold the inquiry here.</p>{!reviews.length && <p className="muted-copy">No inquiries waiting for review.</p>}{reviewData.map(({ receipt, payload, matches }) => <article className="intake-review" key={receipt.id}><h3>{payload.displayName || payload.email || payload.phone || "Incoming inquiry"}</h3><p>{receipt.connection.name} · {payload.email || "No email"} · {payload.phone || "No phone"}</p><p className="muted-copy">{journeyEventLabel(payload.eventType)}. Accepting this inquiry applies your matching journey rules.</p>{payload.message && <p className="preserve-lines">{payload.message}</p>}<form action={reviewIntakeAction} className="form-stack"><input type="hidden" name="receiptId" value={receipt.id} /><label className="field"><span>Matching contact</span><select name="contactId" defaultValue=""><option value="">Choose a matching person</option>{matches.filter(contact => !contact.archivedAt).map(contact => <option key={contact.id} value={contact.id}>{contact.displayName}</option>)}</select></label>{matches.some(contact => contact.archivedAt) && <p className="muted-copy">An archived person matches these details. <Link className="inline-action" href="/contacts/archived">Restore them</Link> to link this inquiry, or create a separate contact if appropriate.</p>}<div className="form-actions"><button className="button primary" name="decision" value="link">Link to selected person</button><button className="button" name="decision" value="create">Create a separate contact</button><button className="button" name="decision" value="ignore">Ignore inquiry</button></div></form></article>)}{reviewCount > reviews.length && <p className="muted-copy">Showing the 10 oldest. Review these to reveal the next inquiries.</p>}</section>
    <section className="card"><h2>Recent inquiries</h2>{recent.length ? <div className="intake-receipts">{recent.map(receipt => { const payload = parseIntakePayload(receipt.payload); return <details key={receipt.id}><summary><span>{receipt.contact?.displayName || payload.displayName || payload.email || "Inquiry"}</span><span>{receipt.connection.name} · {receipt.status === "REVIEW" ? "Needs review" : receipt.status === "ACCEPTED" ? "Received" : "Ignored"}</span></summary><p>Received {receipt.createdAt.toISOString().replace("T", " ").slice(0,16)} UTC</p>{receipt.contact && <Link className="inline-action" href={`/contacts/${receipt.contactId}`}>Open contact</Link>}<dl><dt>Business event</dt><dd>{journeyEventLabel(payload.eventType)}</dd><dt>Source event ID</dt><dd>{receipt.eventKey}</dd><dt>Submitted details</dt><dd>{[payload.displayName,payload.company,payload.email,payload.phone].filter(Boolean).join(" · ") || "Source ID only"}</dd><dt>Message</dt><dd className="preserve-lines">{payload.message || "No message"}</dd></dl></details>; })}</div> : <p className="muted-copy">Connect a source and send a sample inquiry to see its receipt here.</p>}<nav className="calendar-week-nav" aria-label="Inquiry pages">{page > 1 && <Link className="button" href={`/settings/connections?page=${page-1}`}>Previous inquiries</Link>}{page*20 < recentCount && <Link className="button" href={`/settings/connections?page=${page+1}`}>Next inquiries</Link>}</nav></section>
    <details className="card" id="source-guide"><summary>Ways to connect your sources</summary>{INTAKE_KINDS.map(kind => <div className="source-guide-row" key={kind.value}><h3>{kind.label}</h3><p>{kind.hint}</p></div>)}<p>CSV lists and shared .vcf/.vCard files use <Link className="inline-action" href="/contacts/import">Import contacts</Link>. Your phone’s contact picker is in Contacts → More.</p><p className="muted-copy">These are shared connection standards. Native provider sign-in and permissions are managed by the source tool or connector you choose. Platform access and supported triggers vary; this app does not directly read all inboxes or social accounts.</p></details>
    <p className="muted-copy">New inquiries preserve existing contact details, Do not contact preferences, and manual plan stops. Original submitted details remain available in each receipt. Configure <Link className="inline-action" href="/settings/journey">customer journey rules</Link> to choose what happens next.</p>
  </div>;
}
