import type { Metadata } from "next";
import Link from "next/link";
import { PublicDocument } from "@/components/PublicDocument";

export const metadata: Metadata = { title: "Privacy", description: "What Jump in the Mix stores, how it is used, and how you can manage your information." };

export default function PrivacyPage() {
  return <PublicDocument title="Your information and privacy">{details => <>
    <p>{details.operatorName} operates Jump in the Mix. Contact <a href={`mailto:${encodeURIComponent(details.supportEmail)}`}>{details.supportEmail}</a> about your account, privacy, or information someone else has entered about you.</p>
    <section><h2>What you provide</h2><p>We store your account details and the contacts, notes, dates, mixes, follow-up history, and preferences you save. Joining the waitlist records your email and confirmation or access status without creating a customer account. Invitations record the sender, recipient, and access and delivery history. Support conversations contain the information you choose to share.</p><p>Only add information you have permission to use. Avoid adding unnecessary sensitive information to contact notes or support messages.</p></section>
    <section><h2>How we use information</h2><p>We use these records to operate your account, prepare your follow-up list, provide connections and notifications you enable, deliver requested account, invitation, and support emails, answer support requests, and protect the service. Operational records support sending limits, recipient opt-outs, delivery recovery, security, and reliability.</p></section>
    <section><h2>Messages and service providers</h2><p>By default, you review a follow-up and send it through your chosen messaging app. Automatic sending requires a configured provider and your opt-in. Personal invitations are emailed after you choose a recipient and send through the System Mix.</p><p>The production service uses Render for hosting and database storage, Resend for application email, and Amazon Web Services for independently stored encrypted backups and recovery keys. Emails sent to our support address are forwarded through ImprovMX to the operator&apos;s Gmail inbox. These services process the data needed to provide those functions. Resend stores message content and delivery records in the United States. Optional calendar, intake, push, SMS, or sign-in connections also involve the providers you use. Disconnecting a connection does not retract messages or copies already held by a provider or recipient.</p></section>
    <section><h2>Voice and your browser</h2><p>Dictation starts only when you choose it. Your browser may send audio to its speech-recognition provider. Jump in the Mix does not create a raw-audio recording or transcript archive. You can review recognized text and decide whether to save it. The optional spoken Today summary uses a voice your browser identifies as local.</p><p>Temporary capture drafts stay in the current tab for up to ten minutes and are removed when loaded into the destination form. Cookies and account-scoped browser storage support sign-in and application preferences. The current app does not send website usage events to an analytics provider or set an advertising cookie.</p></section>
    <section><h2>Access and support</h2><p>Account and workspace permissions control customer access. Staff permissions limit administrative access and require multifactor authentication. The private support-view workflow requires customer permission and records staff access. Hosting administrators have separate operational access controlled through the infrastructure accounts.</p></section>
    <section><h2>Your choices</h2><p>In Settings → Data &amp; privacy, export your account data or permanently delete your account. You can edit contacts and preferences and turn optional automatic sending or notifications off. Invitation recipients can <Link href="/waitlist/leave">leave the waitlist or stop invitation emails</Link>.</p><p>Contact our support address about information you cannot manage yourself, including information entered by another customer. We need to verify a request before sharing private records or changing an account.</p></section>
    <section><h2>Retention and deletion</h2><p>Saved customer information stays with the account unless deleted. Cleanup removes expired temporary records and ages out operational details. Resolved or closed support conversations become eligible for deletion after 180 inactive days; recent activity and unresolved delivery can extend this. Some email, report, and security details follow activity-based retention windows of up to 400 days. Limited suppression, invitation quota, and replay-prevention records can remain longer so cleanup does not revive unwanted mail or used access. Active invitations and unresolved support work have separate exceptions.</p><p className="public-retention-notice">{details.backupRetentionNotice}</p><p>Our application email provider currently documents 30-day email and log retention for its standard plans, with seven-day backups; early removal of a specific message requires a provider request. ImprovMX forwarding logs are configured to expire after seven days. Support emails in the operator&apos;s mailbox require separate handling from in-app support conversations. Hosting logs follow the selected workspace plan. We track applicable provider and mailbox requests separately from account deletion. Deleting your account does not retract delivered emails or erase files you downloaded.</p></section>
    <section><h2>Changes and questions</h2><p>We update this notice and its effective date when our information practices change. Contact <Link href="/contact">support</Link> with questions or requests.</p></section>
  </>}</PublicDocument>;
}
